version: '3.8'  
services:  
  neo4j:  
    image: neo4j:5.15  
    ports:  
      - "7474:7474"  
      - "7687:7687"  
    environment:  
      - NEO4J_AUTH=neo4j/password  
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:  
      - neo4j_data:/data  
  
  # mongodb:   
  #   image: mongo:7.0  
  #   ports:  
  #     - "27017:27017"  
  #   environment:  
  #     - MONGO_INITDB_ROOT_USERNAME=admin  
  #     - MONGO_INITDB_ROOT_PASSWORD=password  
  #   volumes:  
  #     - mongodb_data:/data/db  
  
volumes:  
  neo4j_data:  
  # mongodb_data: